# Generated by Django 5.1.3 on 2024-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litresmodel',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
