# Generated by Django 5.1.3 on 2024-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/', verbose_name='Загрузите фото книги')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название книги')),
                ('description', models.TextField(blank=True, verbose_name='Укажите описание')),
                ('price', models.FloatField(default=10, verbose_name='Укажите цену')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Роман', 'Роман'), ('Миф', 'Миф'), ('Сказка', 'Сказка')], default='Роман', max_length=100)),
                ('mail', models.CharField(max_length=100, verbose_name='Укажите почту')),
                ('author', models.CharField(max_length=100, verbose_name='Укажите автора')),
                ('trailer', models.URLField(verbose_name='Укажите ссылку на книгу')),
            ],
        ),
    ]
