# Generated by Django 5.1.3 on 2024-12-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_blog', '0002_alter_bookmodel_options_alter_bookmodel_mail_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
