# Generated by Django 5.1.3 on 2024-12-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('library_blog', '0003_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_book', to='library_blog.bookmodel', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='mail',
            field=models.EmailField(max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
    ]
